//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTrackerLibrary.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TimeTrackerLibrary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE [master]
        ///GO
        ////****** Object:  Database [TimeTrackerDbTEST]    Script Date: 1/13/2021 12:01:37 AM ******/
        ///CREATE DATABASE [TimeTrackerDbTEST]
        /// CONTAINMENT = NONE
        /// ON  PRIMARY 
        ///( NAME = N&apos;TimeTrackerDbTEST&apos;, FILENAME = N&apos;C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\TimeTrackerDbTEST_Primary.mdf&apos; , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
        /// LOG ON 
        ///( NAME = N&apos;TimeTrackerDbTEST_log&apos;, FILENAME = N&apos;C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateMSSQLDB {
            get {
                return ResourceManager.GetString("CreateMSSQLDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEGIN TRANSACTION;
        ///CREATE TABLE IF NOT EXISTS &quot;Category&quot; (
        ///	&quot;Id&quot;	INTEGER NOT NULL,
        ///	&quot;Name&quot;	TEXT NOT NULL,
        ///	PRIMARY KEY(&quot;Id&quot; AUTOINCREMENT)
        ///);
        ///CREATE TABLE IF NOT EXISTS &quot;Subcategory&quot; (
        ///	&quot;Id&quot;	INTEGER NOT NULL,
        ///	&quot;Name&quot;	TEXT NOT NULL,
        ///	&quot;CategoryId&quot;	INTEGER,
        ///	PRIMARY KEY(&quot;Id&quot; AUTOINCREMENT),
        ///	FOREIGN KEY(&quot;CategoryId&quot;) REFERENCES &quot;Category&quot;(&quot;Id&quot;)
        ///);
        ///CREATE TABLE IF NOT EXISTS &quot;Project&quot; (
        ///	&quot;Id&quot;	INTEGER NOT NULL,
        ///	&quot;Name&quot;	TEXT NOT NULL,
        ///	&quot;CategoryId&quot;	INTEGER NOT NULL,
        ///	&quot;SubcategoryId&quot;	INTEGER,
        ///	PR [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateSQLiteDB {
            get {
                return ResourceManager.GetString("CreateSQLiteDB", resourceCulture);
            }
        }
    }
}
